name: "Destroy Test Environment"
description: "Runs bbl destroy to tear down the entire test environment"

inputs:
  env_name:
    description: "BBL environment name (state dir under the bbl-state repo)"
    required: true
  bbl_state_repo:
    description: "Repo holding bbl state (owner/repo)"
    required: true
  bbl_state_branch:
    description: "Branch of the bbl state repo"
    required: true
    default: main
  gcp_project_id:
    description: "GCP project ID"
    required: true
  gcp_zone:
    description: 'GCP Zone'
    required: false
    default: 'us-central1-a'
  gcp_region:
    description: 'GCP Region'
    required: false
    default: 'us-central1'

runs:
  using: "composite"
  steps:
    - name: Checkout bbl state repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.bbl_state_repo }}
        ref: ${{ inputs.bbl_state_branch }}
        ssh-key: ${{ env.BBL_STATE_DEPLOY_KEY }}
        path: bbl-state

    - name: Setup tools (bbl)
      shell: bash
      run: |
        set -euo pipefail
        wget -O /tmp/bbl https://github.com/cloudfoundry/bosh-bootloader/releases/download/v9.0.36/bbl-v9.0.36_linux_amd64
        chmod +x /tmp/bbl
        sudo mv /tmp/bbl /usr/local/bin/bbl

    - name: Destroy environment
      shell: bash
      run: |
        set -euo pipefail
        BBL_STATE_DIR="bbl-state/${{ inputs.env_name }}"
        cd "$BBL_STATE_DIR"

        printf "%s" "${GCP_SERVICE_ACCOUNT_KEY}" > gcp-key.json
        export BBL_GCP_SERVICE_ACCOUNT_KEY="$(pwd)/gcp-key.json"
        export BBL_GCP_PROJECT_ID="${{ inputs.gcp_project_id }}"
        export BBL_GCP_ZONE="${{ inputs.gcp_zone }}"
        export BBL_GCP_REGION="${{ inputs.gcp_region }}"
        export BBL_IAAS=gcp

        bbl destroy --no-confirm --state-dir "$BBL_STATE_DIR"

    - name: Commit and push BBL state
      if: always()
      shell: bash
      run: |
        cd bbl-state
        git config user.name "CF Buildpacks Eng Bot"
        git config user.email "test@test.com"
        if [[ -n "$(git status --porcelain)" ]]; then
          git add -A
          git commit -m "Clean up bbl state dir for ${{ inputs.env_name }}"
          git push origin ${{ inputs.bbl_state_branch }}
        else
          echo "No BBL state changes to commit."
        fi
