name: 'Check Rootfs CVEs'
description: 'Check for new CVEs in rootfs - equivalent to Concourse check-for-new-rootfs-cves task'

inputs:
  stack:
    description: 'Stack name (e.g., cflinuxfs5)'
    required: true
  ubuntu_version:
    description: 'Ubuntu version description'
    required: false
    default: 'Ubuntu 22.04'
  ubuntu_codename:
    description: 'Ubuntu codename for CVE checking'
    required: false
    default: 'ubuntu22.04'
  buildpacks_ci_repo:
    description: 'Buildpacks CI repository (owner/repo)'
    required: false
    default: 'ivo1116/buildpacks-ci'
  buildpacks_ci_ref:
    description: 'Buildpacks CI repository ref'
    required: false
    default: 'master'
  buildpacks_ci_path:
    description: 'Path to buildpacks-ci repository'
    required: false
    default: 'buildpacks-ci'
  rootfs_path:
    description: 'Path to rootfs repository'
    required: false
    default: 'rootfs'
  cves_repo_path:
    description: 'Path to CVEs repository'
    required: false
    default: 'new-cves'
  git_user_name:
    description: 'Git user name for commits'
    required: false
    default: 'cflinuxfs-bot'
  git_user_email:
    description: 'Git user email for commits'
    required: false
    default: 'cflinuxfs-bot@test.com'
  github_token:
    description: 'GitHub token for accessing private repos'
    required: false

outputs:
  changes_detected:
    description: 'Whether new CVEs were detected'
    value: ${{ steps.check-changes.outputs.changes }}
  cves_updated:
    description: 'Whether CVE notifications were updated'
    value: ${{ steps.push-changes.outputs.updated }}

runs:
  using: 'composite'
  steps:
    - name: Checkout buildpacks-ci (forked)
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.buildpacks_ci_repo }}
        ref: ${{ inputs.buildpacks_ci_ref }}
        path: ${{ inputs.buildpacks_ci_path }}
        token: ${{ inputs.github_token || github.token }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        working-directory: ${{ inputs.buildpacks_ci_path }}

    - name: Create output directory
      shell: bash
      run: |
        mkdir -p output-new-cves
        rsync -a ${{ inputs.cves_repo_path }}/ output-new-cves/

    - name: Debug bundler and gems
      shell: bash
      run: |
        cd ${{ inputs.buildpacks_ci_path }}
        echo "=== Bundler configuration ==="
        bundle config list
        echo "=== Bundle show nokogiri ==="
        bundle show nokogiri || echo "nokogiri not found via bundle show"
        echo "=== Bundle list (first 10) ==="
        bundle list | head -10
        echo "=== Ruby load path ==="
        bundle exec ruby -e "puts $LOAD_PATH.first(5)"
        echo "=== Test nokogiri require ==="
        bundle exec ruby -e "require 'nokogiri'; puts 'nokogiri loaded successfully'" || echo "Failed to load nokogiri"

    - name: Check for new CVEs
      shell: bash
      run: |
        cd ${{ inputs.buildpacks_ci_path }}
        export STACK='${{ inputs.stack }}'
        export BUILDPACKS_CI_DIR="$(pwd)"
        export STACKS_DIR="$(realpath ../${{ inputs.rootfs_path }})"
        export CVES_DIR="$(realpath ../output-new-cves/new-cve-notifications)"
        
        # Make sure the CVEs directory exists
        mkdir -p "$CVES_DIR"
        
        echo "Running CVE check with:"
        echo "  STACK: $STACK"
        echo "  BUILDPACKS_CI_DIR: $BUILDPACKS_CI_DIR" 
        echo "  STACKS_DIR: $STACKS_DIR"
        echo "  CVES_DIR: $CVES_DIR"
        
        # Check if the rootfs-cve-notifier exists
        if [[ ! -f "./lib/rootfs-cve-notifier.rb" ]]; then
          echo "Error: rootfs-cve-notifier.rb not found in ./lib/"
          find . -name "*cve*" -o -name "*rootfs*" | head -10
          exit 1
        fi
        
        # Debug the Ruby file contents to see what it requires
        echo "=== Checking rootfs-cve-notifier.rb dependencies ==="
        head -10 ./lib/rootfs-cve-notifier.rb
        echo "=== Checking rootfs-cve-feed.rb dependencies ==="
        head -10 ./lib/rootfs-cve-feed.rb
        
        # Run the CVE check with explicit bundler exec
        echo "=== Running CVE notifier ==="
        bundle exec ruby -r "./lib/rootfs-cve-notifier" -e "
          puts 'Loading RootFSCVENotifier...'
          cve_notifier = RootFSCVENotifier.new('$CVES_DIR', '$STACKS_DIR')
          puts 'Running CVE check...'
          cve_notifier.run!('$STACK', '${{ inputs.ubuntu_version }}', '${{ inputs.ubuntu_codename }}', [])
          puts 'CVE check completed.'
        "

    - name: Check for changes
      id: check-changes
      shell: bash
      run: |
        cd output-new-cves
        git config user.name "${{ inputs.git_user_name }}"
        git config user.email "${{ inputs.git_user_email }}"
        
        if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "New CVEs detected for ${{ inputs.stack }}"
          echo "Changed files:"
          git status --porcelain
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No new CVEs found for ${{ inputs.stack }}"
        fi

    - name: Commit and push changes
      id: push-changes
      if: steps.check-changes.outputs.changes == 'true'
      shell: bash
      run: |
        cd output-new-cves
        git add -A
        git commit -m "Update CVE notifications for ${{ inputs.stack }}

        Automated update from rootfs CVE check
        [ci skip]"
        
        if git push origin HEAD; then
          echo "updated=true" >> $GITHUB_OUTPUT
          echo "CVE notifications updated and pushed"
        else
          echo "updated=false" >> $GITHUB_OUTPUT
          echo "Failed to push CVE updates"
          exit 1
        fi

    - name: No changes found
      if: steps.check-changes.outputs.changes == 'false'
      shell: bash
      run: |
        echo "updated=false" >> $GITHUB_OUTPUT
        echo "No CVE updates needed for ${{ inputs.stack }}"
