name: Create Final BOSH Release
description: Create a final BOSH release using the provided rootfs blob
inputs:
  release_dir:
    description: Path to the BOSH release repository
    required: true
  blob_name:
    description: Blobstore directory name (e.g. rootfs)
    required: true
  blob_glob:
    description: Glob for final rootfs tarball (e.g. rootfs-artifacts/cflinuxfs5-*.tar.gz)
    required: true
  release_name:
    description: BOSH release name
    required: true
  version:
    description: Release version to finalize
    required: true

runs:
  using: composite
  steps:
    - name: Install BOSH CLI
      shell: bash
      run: |
        set -euo pipefail
        ver="7.5.6"
        url="https://github.com/cloudfoundry/bosh-cli/releases/download/v${ver}/bosh-cli-${ver}-linux-amd64"
        curl -fsSL "$url" -o bosh
        chmod +x bosh
        sudo mv bosh /usr/local/bin/bosh
        bosh --version

    - name: Add final rootfs blob
      shell: bash
      run: |
        set -euo pipefail
        pushd "${{ inputs.release_dir }}"
          # Only add the final tarball (not RCs)
          for f in ../${{ inputs.blob_glob }}; do
            test -f "$f" || { echo "Missing blob $f"; exit 1; }
            base=$(basename "$f")
            echo "Adding blob: $base"
            bosh add-blob "$f" "${{ inputs.blob_name }}/${base}"
          done
        popd

    - name: Create final BOSH release
      shell: bash
      run: |
        set -euo pipefail
        pushd "${{ inputs.release_dir }}"
          mkdir -p ../release-artifacts
          bosh -n create-release --final \
            --name "${{ inputs.release_name }}" \
            --version "${{ inputs.version }}" \
            --tarball "../release-artifacts/${{ inputs.release_name }}-${{ inputs.version }}.tgz" \
            --force
        popd
