name: 'Deploy CF'
description: 'Deploy Cloud Foundry with new rootfs - equivalent to Concourse deploy job'

inputs:
  stack:
    description: 'Stack name'
    required: true
  version:
    description: 'Version number'
    required: true
  env_name:
    description: 'Environment name'
    required: false
    default: 'cflinuxfs5'
  system_domain:
    description: 'System domain'
    required: false
    default: 'cflinuxfs5.buildpacks-gcp.ci.cf-app.com'
  bbl_state_repo:
    description: 'Repo for BBL state (owner/repo)'
    required: true
  bbl_state_branch:
    description: 'Branch for BBL state'
    required: false
    default: 'main'

outputs:
  success:
    description: 'Whether CF deployment succeeded'
    value: ${{ steps.deploy.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Checkout cf-deployment
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/cf-deployment
        ref: v21.11.0
        path: cf-deployment

    - name: Checkout buildpacks-ci
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/buildpacks-ci
        ref: master
        path: buildpacks-ci

    - name: Checkout cflinuxfs5-release
      uses: actions/checkout@v4
      with:
        repository: ivo1116/cflinuxfs5-release
        ref: main
        path: cflinuxfs5-release
        token: ${{ env.CFLINUXFS5_TOKEN }}

    - name: Checkout CAPI release
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/capi-release
        ref: main
        path: capi-release
        submodules: recursive

    - name: Checkout BBL state repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.bbl_state_repo }}
        ref: ${{ inputs.bbl_state_branch }}
        path: bbl-state
        ssh-key: ${{ env.BBL_STATE_DEPLOY_KEY }}

    - name: Download cflinuxfs5 rootfs from S3
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1 

      run: |
        aws s3 cp s3://cflinuxfs5test/cflinuxfs5-1.0.0-rc.1.tar.gz rootfs-artifacts/cflinuxfs5-1.0.0-rc.1.tar.gz

    - name: Get GCP stemcell
      shell: bash
      run: |
        wget -O gcp-stemcell.tgz "https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-noble?v=1.25"

    - name: Install BBL & bosh
      shell: bash
      run: |
        set -euo pipefail
        wget -O /tmp/bbl https://github.com/Ivo1116/bosh-bootloader/releases/download/test/bbl-linux
        chmod +x /tmp/bbl
        sudo mv /tmp/bbl /usr/local/bin/bbl

        wget -O /tmp/bosh https://github.com/cloudfoundry/bosh-cli/releases/download/v7.4.0/bosh-cli-7.4.0-linux-amd64
        chmod +x /tmp/bosh
        sudo mv /tmp/bosh /usr/local/bin/bosh

    - name: Create deployment source config
      shell: bash
      run: |
        cd bbl-state

        cd cflinuxfs5

        mkdir ../../deployment-source-config

        bbl print-env > ../../deployment-source-config/source_file.yml

    - name: Overwrite rootfs release
      shell: bash
      run: |
        cd buildpacks-ci
        
        export STACK='${{ inputs.stack }}'
        
        mkdir -p ../rootfs-release-artifacts
        
        cd ../cflinuxfs5-release
        
        if [[ -f "../rootfs-artifacts/${{ inputs.stack }}-${{ inputs.version }}.tar.gz" ]]; then
          bosh create-release --force --tarball=../rootfs-release-artifacts/cflinuxfs5-dev.tgz
        fi

    - name: Upload ubuntu-noble stemcell
      shell: bash
      run: |
        cd deployment-source-config
        source source_file.yml
        cd ..
        bosh upload-stemcell gcp-stemcell.tgz --non-interactive

    - name: Upload cflinuxfs5 release to BOSH director
      shell: bash
      run: |
        cd deployment-source-config
        source source_file.yml
        cd ..
        bosh upload-release rootfs-artifacts/cflinuxfs5-1.0.0-rc.1.tar.gz --non-interactive

    - name: Create CAPI release with rootfs
      shell: bash
      run: |
        cd buildpacks-ci
        
        export STACK='${{ inputs.stack }}'
        
        mkdir -p ../capi-release-artifacts
        
        cd ../capi-release
        bosh create-release --force --tarball=../capi-release-artifacts/capi-dev.tgz

    - name: Use new buildpack BOSH releases
      shell: bash
      run: |
        cd buildpacks-ci
        
        mkdir -p ../built-buildpacks-artifacts ../buildpacks-opsfile
        
        cat > ../buildpacks-opsfile/use-latest-buildpack-releases.yml << 'EOF'
        EOF

    - name: Copy rootfs smoke test manifest
      shell: bash
      run: |
        mkdir -p rootfs-release-artifacts/manifests
        cp cflinuxfs5-release/manifests/manifest.yml rootfs-release-artifacts/manifests/manifest.yml

    - name: Deploy rootfs smoke test
      shell: bash
      run: |
        cd deployment-source-config
        source source_file.yml

        bosh -d rootfs-smoke-test deploy \
        ../rootfs-release-artifacts/manifests/manifest.yml \
        --vars-store smoke-test-vars.yml \
        --non-interactive

    - name: Run rootfs smoke test
      shell: bash
      run: |
        set -euo pipefail

        cd deployment-source-config
        source source_file.yml
        cd ..

        bosh -d rootfs-smoke-test run-errand smoke-tests

    - name: Deploy CF
      id: deploy
      shell: bash
      run: |
        set -euo pipefail
        
        cd deployment-source-config
        source source_file.yml
        
        bosh -d cf deploy ../cf-deployment/cf-deployment.yml \
          --ops-file ../cf-deployment/operations/experimental/fast-deploy-with-downtime-and-danger.yml \
          --ops-file ../cf-deployment/operations/use-latest-stemcell.yml \
          --ops-file ../cf-deployment/operations/use-compiled-releases.yml \
          --ops-file ../cf-deployment/operations/experimental/add-cflinuxfs5.yml \
          --ops-file ../cf-deployment/operations/experimental/set-cflinuxfs5-default-stack.yml \
          --ops-file ../buildpacks-opsfile/use-latest-buildpack-releases.yml \
          --ops-file ../rootfs-release-artifacts/use-dev-release-opsfile.yml \
          --ops-file ../capi-release-artifacts/use-dev-release-opsfile.yml \
          --var system_domain='${{ inputs.system_domain }}' \
          --vars-store cf-vars.yml

        echo "success=true" >> $GITHUB_OUTPUT
