name: 'Update Version in S3'
description: 'Write version string to an S3 key (versions file)'

inputs:
  bucket-name:
    description: 'S3 bucket name'
    required: true
  key:
    description: 'S3 object key to write (e.g., versions/stack-cflinuxfs5)'
    required: true
  version:
    description: 'Version string to write'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Write version to S3
      shell: bash
      run: |
        set -euo pipefail
        TMP="$(mktemp)"
        echo "${{ inputs.version }}" > "$TMP"
        aws s3 cp "$TMP" "s3://${{ inputs.bucket-name }}/${{ inputs.key }}" \
          --no-progress --content-type text/plain
