name: Check for New Rootfs CVEs
description: Runs the CVE notifier for cflinuxfs5
inputs:
  buildpacks-ci-path:
    description: Path to buildpacks-ci repo
    required: true
  new-cves-path:
    description: Path to new-cves repo
    required: true
  cflinuxfs5-path:
    description: Path to cflinuxfs5 repo
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh
        ${{ github.action_path }}/entrypoint.sh \
          "${{ inputs.buildpacks-ci-path }}" \
          "${{ inputs.new-cves-path }}" \
          "${{ inputs.cflinuxfs5-path }}"
      shell: bash