name: 'Upload to S3'
description: 'Upload artifacts to S3 - equivalent to Concourse upload-s3 task'

inputs:
  upload-type:
    description: 'Type of upload (stack-s3, receipt-s3, or release-s3)'
    required: true
  version:
    description: 'Version number'
    required: true
  bucket-name:
    description: 'S3 bucket name'
    required: true
  file:
    description: 'Optional: explicit file path to upload (used for release-s3)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload to S3
      shell: bash
      run: |
        set -euo pipefail

        VERSION="${{ inputs.version }}"
        UPLOAD_TYPE="${{ inputs.upload-type }}"
        BUCKET="${{ inputs.bucket-name }}"
        FILE_INPUT="${{ inputs.file }}"

        case "$UPLOAD_TYPE" in
          "stack-s3")
            STACK_FILE="rootfs-artifacts/cflinuxfs5-${VERSION}.tar.gz"
            if [ ! -f "$STACK_FILE" ]; then
              echo "ERROR: Stack file not found: $STACK_FILE"
              ls -la rootfs-artifacts/ || echo "No rootfs-artifacts directory"
              exit 1
            fi

            echo "Uploading stack tarball to S3..."
            aws s3 cp "$STACK_FILE" \
              "s3://${BUCKET}/rootfs/" \
              --content-type application/gzip \
              --metadata version="${VERSION}"
            ;;

          "receipt-s3")
            RECEIPT_FILE="receipt-artifacts/receipt.cflinuxfs5.x86_64-${VERSION}"
            if [ ! -f "$RECEIPT_FILE" ]; then
              echo "ERROR: Receipt file not found: $RECEIPT_FILE"
              ls -la receipt-artifacts/ || echo "No receipt-artifacts directory"
              exit 1
            fi

            echo "Uploading receipt to S3..."
            aws s3 cp "$RECEIPT_FILE" \
              "s3://${BUCKET}/rootfs/" \
              --content-type text/plain \
              --metadata version="${VERSION}"
            ;;

          "release-s3")
            # Either use provided file input or default path
            RELEASE_FILE="${FILE_INPUT:-rootfs-artifacts/cflinuxfs5-release-${VERSION}.tgz}"
            if [ ! -f "$RELEASE_FILE" ]; then
              echo "ERROR: Release file not found: $RELEASE_FILE"
              ls -la rootfs-artifacts/ || echo "No rootfs-artifacts directory"
              exit 1
            fi

            echo "Uploading BOSH release tarball to S3..."
            aws s3 cp "$RELEASE_FILE" \
              "s3://${BUCKET}/rootfs/" \
              --content-type application/gzip \
              --metadata version="${VERSION}"
            ;;

          *)
            echo "ERROR: Unknown upload type: $UPLOAD_TYPE"
            exit 1
            ;;
        esac

    - name: Verify upload
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        UPLOAD_TYPE="${{ inputs.upload-type }}"
        BUCKET="${{ inputs.bucket-name }}"
        FILE_INPUT="${{ inputs.file }}"

        case "$UPLOAD_TYPE" in
          "stack-s3")
            echo "Verifying stack upload..."
            aws s3 ls "s3://${BUCKET}/rootfs/cflinuxfs5-${VERSION}.tar.gz" || \
              (echo "ERROR: Stack file not found in S3" && exit 1)
            ;;
          "receipt-s3")
            echo "Verifying receipt upload..."
            aws s3 ls "s3://${BUCKET}/rootfs/receipt.cflinuxfs5.x86_64-${VERSION}" || \
              (echo "ERROR: Receipt file not found in S3" && exit 1)
            ;;
          "release-s3")
            RELEASE_FILE_NAME="$(basename ${FILE_INPUT:-cflinuxfs5-release-${VERSION}.tgz})"
            echo "Verifying release upload..."
            aws s3 ls "s3://${BUCKET}/rootfs/${RELEASE_FILE_NAME}" || \
              (echo "ERROR: Release file not found in S3" && exit 1)
            ;;
        esac

        echo "Upload verified successfully"
