name: Bump Next Minor RC
description: Compute the next minor version as X.(Y+1).0-rc.1 from a final
inputs:
  final_version:
    description: Final semver (e.g. 1.2.3)
    required: true
outputs:
  next_rc:
    description: Next RC version (e.g. 1.3.0-rc.1)
    value: ${{ steps.bump.outputs.next_rc }}
runs:
  using: composite
  steps:
    - id: bump
      shell: bash
      run: |
        ver="${{ inputs.final_version }}"
        IFS='.' read -r major minor patch <<< "$ver"
        next_minor=$((minor + 1))
        next="${major}.${next_minor}.0-rc.1"
        echo "next_rc=$next" >> "$GITHUB_OUTPUT"
