name: 'Update Repositories'
description: 'Update repositories with diff - equivalent to Concourse update-repos task'

inputs:
  version:
    description: 'Version number'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout public-robots
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/public-buildpacks-ci-robots
        ref: main
        path: public-robots
        token: ${{ env.PUBLIC_ROBOTS_TOKEN }}
        
    - name: Create version file
      shell: bash
      run: |
        mkdir -p version
        echo "${{ inputs.version }}" > version/number
        
    - name: Update repositories with diff
      shell: bash
      run: |
        set -euo pipefail
        
        VERSION="${{ inputs.version }}"
        
        # Check if we have diff artifacts
        if [ -d "public-robots-artifacts" ] && [ -f "public-robots-artifacts/receipt-diff-${VERSION}.txt" ]; then
          echo "Found receipt diff, updating repositories..."
          
          # Copy diff to public-robots directory
          cp -r public-robots-artifacts/* public-robots/ || true
          
          cd public-robots
          
          # Configure git
          git config user.name "CF Buildpacks CI"
          git config user.email "cf-buildpacks-ci@cloudfoundry.org"
          
          # Create or update branch
          BRANCH_NAME="update-cflinuxfs5-${VERSION}"
          git checkout -b "$BRANCH_NAME" || git checkout "$BRANCH_NAME"
          
          # Add changes
          git add -A
          
          # Commit if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update cflinuxfs5 to ${VERSION}

            - Updated receipt diff
            - Version: ${VERSION}
            - Automated update from cflinuxfs5 pipeline"
            
            # Push changes
            git push origin "$BRANCH_NAME" || echo "Push failed, continuing..."
            
            echo "Repository updated successfully"
          fi
        else
          echo " No diff artifacts found, skipping repository update"
        fi
        
    - name: Create GitHub release
      uses: actions/github-script@v7
      with:
        github-token: ${{ env.CFLINUXFS5_TOKEN }}
        script: |
          const version = '${{ inputs.version }}';
          const fs = require('fs');
          
          try {
            // Check if receipt diff exists
            const diffPath = `public-robots-artifacts/receipt-summary-${version}.txt`;
            let releaseBody = `Release cflinuxfs5 ${version}`;
            
            if (fs.existsSync(diffPath)) {
              const diffContent = fs.readFileSync(diffPath, 'utf8');
              releaseBody += `\n\n## Changes\n\n\`\`\`\n${diffContent}\n\`\`\``;
            }
            
            // Create release
            const release = await github.rest.repos.createRelease({
              owner: 'cloudfoundry',
              repo: 'cflinuxfs5',
              tag_name: version,
              name: `cflinuxfs5 ${version}`,
              body: releaseBody,
              draft: false,
              prerelease: version.includes('-rc')
            });
            
            console.log(`Created release: ${release.data.html_url}`);
            
          } catch (error) {
            console.error('Error creating release:', error);
            // Don't fail the workflow if release creation fails
          }
