name: 'Download from S3'
description: 'Download artifacts from S3'

inputs:
  stack:
    description: 'Stack name'
    required: true
  version:
    description: 'Version number'
    required: true
  bucket-name:
    description: 'S3 bucket name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Download rootfs from S3
      shell: bash
      run: |
        set -euo pipefail
        STACK="${{ inputs.stack }}"
        VERSION="${{ inputs.version }}"
        BUCKET="${{ inputs.bucket-name }}"

        mkdir -p rootfs-artifacts
        echo "Downloading s3://${BUCKET}/rootfs/${STACK}-${VERSION}.tar.gz"
        aws s3 cp "s3://${BUCKET}/rootfs/${STACK}-${VERSION}.tar.gz" "rootfs-artifacts/${STACK}-${VERSION}.tar.gz"
