name: Finalize Version
description: Convert RC version to final version
inputs:
  rc_version:
    description: RC version to finalize (e.g. 1.2.3-rc.4)
    required: true
outputs:
  final_version:
    description: Final version without RC suffix
    value: ${{ steps.calc.outputs.final_version }}
runs:
  using: composite
  steps:
    - id: calc
      shell: bash
      run: |
        ver="${{ inputs.rc_version }}"
        if [[ "$ver" =~ ^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
          final="${ver%-rc.*}"
        else
          final="$ver"
        fi
        echo "final_version=$final" >> "$GITHUB_OUTPUT"
