name: 'Make Rootfs'
description: 'Build rootfs tarball - equivalent to Concourse make-rootfs task'

inputs:
  stack:
    description: 'Stack name'
    required: true
  version:
    description: 'Version number'
    required: true
  privileged:
    description: 'Run with privileged access'
    required: false
    default: 'false'

outputs:
  artifacts-path:
    description: 'Path to generated artifacts'
    value: ${{ steps.build.outputs.artifacts-path }}
  success:
    description: 'Build success status'
    value: ${{ steps.build.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Install system dependencies for nokogiri and Ruby native extensions
      shell: bash
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc \
          make \
          patch \
          ruby-dev \
          zlib1g-dev \
          liblzma-dev \
          libxml2-dev \
          libxslt1-dev \
          libgmp-dev \
          libffi-dev \
          netbase \
          wget \
          curl \
          pkg-config \
          libxml2 \
          libxslt1.1

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.8'
        bundler-cache: false  # Disable cache since we're modifying Gemfile
        working-directory: buildpacks-ci

    - name: Patch Gemfile for Ruby 3.2 compatibility
      shell: bash
      run: |
        cd buildpacks-ci
        
        # Remove ruby version constraint
        sed -i.bak '/^ruby/d' Gemfile
        
        # Add missing Ruby 3.2 dependencies
        echo "gem 'net-ftp'" >> Gemfile
        echo "gem 'net-smtp'" >> Gemfile
        
        # Update nokogiri to compatible version
        sed -i 's/gem.*nokogiri.*/gem "nokogiri", "~> 1.15.0"/' Gemfile || echo 'gem "nokogiri", "~> 1.15.0"' >> Gemfile
        
        # Remove Gemfile.lock to force regeneration
        rm -f Gemfile.lock
        
        # Disable deployment mode for this build
        bundle config unset deployment
        
        # Install gems (this will create new Gemfile.lock)
        bundle install
        
    - name: Setup Docker Buildx
      if: inputs.privileged == 'true'
      uses: docker/setup-buildx-action@v3
      
    - name: Build rootfs
      id: build
      shell: bash
      run: |
        set -euo pipefail
        
        # Create output directories
        mkdir -p rootfs-artifacts
        mkdir -p receipt-artifacts
        
        # Execute build (equivalent to Concourse task)
        cd buildpacks-ci
        bundle exec ruby tasks/make-rootfs.rb \
          --stack=${{ inputs.stack }} \
          --version=${{ inputs.version }} \
          --privileged=${{ inputs.privileged }} \
          --output-dir=../rootfs-artifacts \
          --receipt-dir=../receipt-artifacts
        
        echo "artifacts-path=." >> $GITHUB_OUTPUT
        echo "success=true" >> $GITHUB_OUTPUT
