name: "Cleanup CF Deployments"
description: "Deletes CF and rootfs smoke test deployments from a BBL environment"

inputs:
  stack:
    description: "Stack name (e.g. cflinuxfs5)"
    required: true
  bbl_state_repo:
    description: Repo holding bbl state (owner/repo)
    required: true
  bbl_state_branch:
    description: Branch of the bbl state repo
    required: true
    default: main

runs:
  using: "composite"
  steps:
    - name: Checkout bbl state repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.bbl_state_repo }}
        ref: ${{ inputs.bbl_state_branch }}
        ssh-key: ${{ env.BBL_STATE_DEPLOY_KEY }}
        path: bbl-state

    - name: Setup tools (bosh, bbl)
      shell: bash
      run: |
        set -euo pipefail
        wget -O /tmp/bbl https://github.com/cloudfoundry/bosh-bootloader/releases/download/v9.0.36/bbl-v9.0.36_linux_amd64
        chmod +x /tmp/bbl
        sudo mv /tmp/bbl /usr/local/bin/bbl

        wget -O /tmp/bosh https://github.com/cloudfoundry/bosh-cli/releases/download/v7.4.0/bosh-cli-7.4.0-linux-amd64
        chmod +x /tmp/bosh
        sudo mv /tmp/bosh /usr/local/bin/bosh

    - name: Delete CF deployments
      shell: bash
      run: |
        set -euo pipefail
        BBL_STATE_DIR="bbl-state/${{ inputs.stack }}"

        eval "$(bbl print-env --state-dir "$BBL_STATE_DIR")"

        bosh delete-deployment -d cf
