name: Bump Golang Package

on:
  workflow_dispatch:

jobs:
  bump-golang:
    runs-on: ubuntu-latest
    env:
      GIT_USER_NAME: cf-buildpacks-eng
      GIT_USER_EMAIL: cf-buildpacks-eng@pivotal.io
      CLOUD_FOUNDRY_S3_ACCESS_KEY: ${{ secrets.CLOUD_FOUNDRY_S3_ACCESS_KEY }}
      CLOUD_FOUNDRY_S3_SECRET_KEY: ${{ secrets.CLOUD_FOUNDRY_S3_SECRET_KEY }}
    steps:
      - name: Checkout cflinuxfs5-release
        uses: actions/checkout@v4
        with:
          repository: plamen-bardarov/cflinuxfs5-release
          path: cflinuxfs5-release
          token: ${{ secrets.CFLINUXFS5_TOKEN }}

      - name: Checkout golang-release
        uses: actions/checkout@v4
        with:
          repository: cloudfoundry/bosh-package-golang-release
          path: golang-release

      - name: Bump Golang Package
        uses: ./.github/actions/bump-golang-package
        with:
          cflinuxfs5-release-path: cflinuxfs5-release
          golang-release-path: golang-release
          git_user_name: ${{ env.GIT_USER_NAME }}
          git_user_email: ${{ env.GIT_USER_EMAIL }}
          packages: '["golang-1-linux"]'
          packages_to_remove: '[]'
          private_yml: |
            ---
            blobstore:
              options:
                access_key_id: ${{ env.CLOUD_FOUNDRY_S3_ACCESS_KEY }}
                secret_access_key: ${{ env.CLOUD_FOUNDRY_S3_SECRET_KEY }}
          release_dir: '.'

      - name: Push changes if any
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump golang package"
          branch: main
          repository: cflinuxfs5-release
          token: ${{ secrets.CFLINUXFS5_TOKEN }}