name: Task - Upload to S3

on:
  workflow_call:
    inputs:
      upload-type:
        required: true
        type: string
      version:
        required: true
        type: string
      artifacts-path:
        required: true
        type: string

jobs:
  upload:
    name: Upload ${{ inputs.upload-type }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: rootfs-build-${{ inputs.version }}
          path: ./
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Upload to S3
        run: |
          case "${{ inputs.upload-type }}" in
            "stack-s3")
              aws s3 cp rootfs-artifacts/cflinuxfs4-*.tar.gz \
                s3://buildpacks.cloudfoundry.org/rootfs/ \
                --content-type application/gzip
              ;;
            "receipt-s3")
              aws s3 cp receipt-artifacts/receipt.cflinuxfs4.x86_64-* \
                s3://buildpacks.cloudfoundry.org/rootfs/ \
                --content-type text/plain
              ;;
          esac
