name: Task - Generate Receipt Diff

on:
  workflow_call:
    inputs:
      stack:
        required: true
        type: string
      version:
        required: true
        type: string
      previous-version:
        required: true
        type: string
      artifacts-path:
        required: true
        type: string
    outputs:
      diff-path:
        description: "Path to generated diff"
        value: ${{ jobs.generate-diff.outputs.diff-path }}

jobs:
  generate-diff:
    name: Generate Receipt Diff
    runs-on: ubuntu-latest
    outputs:
      diff-path: ${{ steps.diff.outputs.diff-path }}
    
    steps:
      - name: Checkout buildpacks-ci
        uses: actions/checkout@v4
        with:
          repository: cloudfoundry/buildpacks-ci
          ref: master
          path: buildpacks-ci
          
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: rootfs-build-${{ inputs.version }}
          path: ./
          
      - name: Generate diff
        id: diff
        uses: ./buildpacks-ci/.github/actions/generate-receipt-diff
        with:
          stack: ${{ inputs.stack }}
          version: ${{ inputs.version }}
          previous-version: ${{ inputs.previous-version }}
          
      - name: Upload diff artifacts
        uses: actions/upload-artifact@v4
        with:
          name: receipt-diff-${{ inputs.version }}
          path: public-robots-artifacts/
