name: 'BBL Up'
description: 'Set up test environment using BBL (GCP)'

inputs:
  stack:
    description: 'Stack name'
    required: true
  version:
    description: 'Version number'
    required: true
  env_name:
    description: 'Environment name'
    required: false
    default: 'cflinuxfs5-test'
  gcp_project_id:
    description: 'GCP Project ID'
    required: true
  gcp_zone:
    description: 'GCP Zone'
    required: false
    default: 'us-east1-c'
  gcp_region:
    description: 'GCP Region'
    required: false
    default: 'us-east1'
  lb_domain:
    description: 'Load balancer domain'
    required: false
    default: ''
  bbl_state_repo:
    description: 'Repo for BBL state (owner/repo)'
    required: true
  bbl_state_branch:
    description: 'Branch for BBL state'
    required: false
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Checkout cf-deployment-concourse-tasks
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/cf-deployment-concourse-tasks
        ref: main
        path: cf-deployment-concourse-tasks

    - name: Checkout bosh-deployment
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/bosh-deployment
        ref: master
        path: bosh-deployment

    - name: Checkout BBL state repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.bbl_state_repo }}
        ref: ${{ inputs.bbl_state_branch }}
        path: bbl-state
        ssh-key: ${{ env.BBL_STATE_DEPLOY_KEY }}

    - name: Install BBL, Terraform, BOSH CLI
      shell: bash
      run: |
        set -euo pipefail
        wget -O /tmp/bbl https://github.com/Ivo1116/bosh-bootloader/releases/download/test/bbl-linux
        chmod +x /tmp/bbl
        sudo mv /tmp/bbl /usr/local/bin/bbl

        wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        unzip /tmp/terraform.zip -d /tmp/
        sudo mv /tmp/terraform /usr/local/bin/terraform
        sudo chmod +x /usr/local/bin/terraform
        export PATH=$PATH:/usr/local/bin
        terraform version

        wget -O /tmp/bosh https://github.com/cloudfoundry/bosh-cli/releases/download/v7.4.0/bosh-cli-7.4.0-linux-amd64
        chmod +x /tmp/bosh
        sudo mv /tmp/bosh /usr/local/bin/bosh

    - name: Run BBL Up
      id: bbl-up
      shell: bash
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ env.GCP_SERVICE_ACCOUNT_KEY }}
        CFLINUXFS5_LB_CERT: ${{ env.CFLINUXFS5_LB_CERT }}
        CFLINUXFS5_LB_KEY: ${{ env.CFLINUXFS5_LB_KEY }}
      run: |
        set -euo pipefail

        mkdir -p bbl-state/${{ inputs.env_name }}
        cd bbl-state/${{ inputs.env_name }}

        # Write GCP service account key to file
        echo "${GCP_SERVICE_ACCOUNT_KEY}" > gcp-key.json

        export BBL_GCP_SERVICE_ACCOUNT_KEY="$(pwd)/gcp-key.json"
        export BBL_GCP_PROJECT_ID="${{ inputs.gcp_project_id }}"
        export BBL_GCP_ZONE="${{ inputs.gcp_zone }}"
        export BBL_GCP_REGION="${{ inputs.gcp_region }}"
        export BBL_IAAS=gcp

        # Ensure no proxy environment variables interfere
        unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY

        # Set longer timeout for BOSH operations
        export BOSH_CLIENT_TIMEOUT=600
        export BOSH_DEPLOYMENT_TIMEOUT=3600

        # Optional: set LB cert/key if provided
        if [[ -n "${CFLINUXFS5_LB_CERT:-}" && -n "${CFLINUXFS5_LB_KEY:-}" ]]; then
          echo "${CFLINUXFS5_LB_CERT}" > lb-cert.pem
          echo "${CFLINUXFS5_LB_KEY}" > lb-key.pem
          export BBL_LB_CERT="$(pwd)/lb-cert.pem"
          export BBL_LB_KEY="$(pwd)/lb-key.pem"
        fi

        # Optional: set LB domain if provided
        if [[ -n "${{ inputs.lb_domain }}" ]]; then
          export LB_DOMAIN="${{ inputs.lb_domain }}"
        fi

        # Function to test jumpbox connectivity after BBL creates it
        test_jumpbox_connectivity() {
          local max_attempts=30
          local attempt=1
          
          echo "Testing jumpbox connectivity..."
          
          while [ $attempt -le $max_attempts ]; do
            echo "Connectivity test attempt $attempt of $max_attempts"
            
            # Try to get jumpbox info
            if JUMPBOX_ADDRESS=$(bbl jumpbox-address 2>/dev/null) && [[ -n "$JUMPBOX_ADDRESS" ]]; then
              JUMPBOX_IP=$(echo "$JUMPBOX_ADDRESS" | cut -d: -f1)
              
              # Test SSH connectivity
              if bbl ssh-key > /tmp/jumpbox_ssh_key 2>/dev/null; then
                chmod 600 /tmp/jumpbox_ssh_key
                
                if timeout 10 ssh -i /tmp/jumpbox_ssh_key \
                  -o StrictHostKeyChecking=no \
                  -o UserKnownHostsFile=/dev/null \
                  -o ConnectTimeout=10 \
                  -o BatchMode=yes \
                  jumpbox@"$JUMPBOX_IP" \
                  "echo 'Jumpbox is ready'" 2>/dev/null; then
                  echo "Jumpbox is accessible and ready at $JUMPBOX_IP"
                  rm -f /tmp/jumpbox_ssh_key
                  return 0
                fi
                rm -f /tmp/jumpbox_ssh_key
              fi
            fi
            
            echo "Jumpbox not ready yet, waiting..."
            sleep 10
            attempt=$((attempt + 1))
          done
          
          echo "Jumpbox connectivity test failed after $max_attempts attempts"
          return 1
        }

        # Function to prepare jumpbox for better SOCKS5 stability
        prepare_jumpbox() {
          echo "Preparing jumpbox for improved stability..."
          
          if ! JUMPBOX_ADDRESS=$(bbl jumpbox-address 2>/dev/null) || [[ -z "$JUMPBOX_ADDRESS" ]]; then
            echo "Could not get jumpbox address"
            return 1
          fi
          
          JUMPBOX_IP=$(echo "$JUMPBOX_ADDRESS" | cut -d: -f1)
          
          if ! bbl ssh-key > /tmp/jumpbox_ssh_key 2>/dev/null; then
            echo "Could not get jumpbox SSH key"
            return 1
          fi
          
          chmod 600 /tmp/jumpbox_ssh_key
          
          # Configure SSH for better stability
          if ssh -i /tmp/jumpbox_ssh_key \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -o ConnectTimeout=30 \
            jumpbox@"$JUMPBOX_IP" << 'EOF'
        # Update SSH configuration for stability
        sudo sed -i 's/#ClientAliveInterval 0/ClientAliveInterval 60/' /etc/ssh/sshd_config
        sudo sed -i 's/#ClientAliveCountMax 3/ClientAliveCountMax 10/' /etc/ssh/sshd_config
        sudo sed -i 's/#TCPKeepAlive yes/TCPKeepAlive yes/' /etc/ssh/sshd_config
        
        # Make sure changes are applied
        if ! sudo systemctl restart ssh; then
          sudo service ssh restart
        fi

        # Test connectivity to S3
        echo "Testing S3 connectivity from jumpbox..."
        curl -s --connect-timeout 30 --max-time 60 https://s3.amazonaws.com/ > /dev/null && echo "S3 connectivity OK" || echo "S3 connectivity test failed"
        
        # Wait a moment for SSH to be fully ready
        sleep 5
        EOF
          then
            echo "Jumpbox preparation completed successfully"
            rm -f /tmp/jumpbox_ssh_key
            return 0
          else
            echo "Jumpbox preparation failed"
            rm -f /tmp/jumpbox_ssh_key
            return 1
          fi
        }

        # Function to clean up failed BBL state
        cleanup_failed_state() {
          echo "Cleaning up failed BBL state..."
          
          # Try to destroy any partially created resources
          if [ -f bbl-state.json ]; then
            bbl destroy --no-confirm || echo "BBL destroy failed or nothing to destroy"
          fi
          
          # Clean up local state files
          rm -f bbl-state.json terraform.tfstate* create-jumpbox.sh create-director.sh
          rm -rf .terraform/ terraform/ vars/
          
          echo "Cleanup completed"
        }

        # Run BBL up with enhanced error handling
        max_attempts=3
        attempt=1
        
        while [ $attempt -le $max_attempts ]; do
          echo "BBL up attempt $attempt of $max_attempts"
          
          # Clean up any previous failed state
          if [ $attempt -gt 1 ]; then
            cleanup_failed_state
            echo "Waiting 30 seconds before retry..."
            sleep 30
          fi
          
          # Run BBL up
          if bbl up --debug \
            --terraform-binary /usr/local/bin/terraform \
            ${BBL_LB_CERT:+--lb-cert "$BBL_LB_CERT"} \
            ${BBL_LB_KEY:+--lb-key "$BBL_LB_KEY"} \
            ${LB_DOMAIN:+--lb-domain "$LB_DOMAIN"}; then
            echo "BBL up succeeded on attempt $attempt"
            break
          else
            echo "BBL up failed on attempt $attempt"
            
            # Check if we have a jumpbox and can test connectivity
            if bbl jumpbox-address >/dev/null 2>&1; then
              echo "Jumpbox exists, testing connectivity..."
              if test_jumpbox_connectivity; then
                echo "Jumpbox is accessible, preparing for retry..."
                prepare_jumpbox || echo "Jumpbox preparation failed"
              else
                echo "Jumpbox connectivity test failed"
              fi
            else
              echo "No jumpbox found, infrastructure creation may have failed"
            fi
            
            if [ $attempt -eq $max_attempts ]; then
              echo "All BBL up attempts failed"
              cleanup_failed_state
              exit 1
            fi
            
            attempt=$((attempt + 1))
          fi
        done

        # Final connectivity test
        echo "Performing final connectivity test..."
        if test_jumpbox_connectivity; then
          echo "Final jumpbox connectivity test passed"
        else
          echo "Warning: Final jumpbox connectivity test failed, but BBL up succeeded"
        fi

        echo "success=true" >> $GITHUB_OUTPUT

    - name: Commit and push BBL state
      shell: bash
      run: |
        set -euo pipefail
        cd bbl-state
        git config user.name "CF Buildpacks Eng Bot"
        git config user.email "tanzu-buildpacks.pdl@broadcom.com"
        if [[ -n "$(git status --porcelain)" ]]; then
          git add -A
          git commit -m "Update BBL state for ${{ inputs.env_name }}"
          git push origin ${{ inputs.bbl_state_branch }}
        else
          echo "No BBL state changes to commit."
        fi

    - name: Output BBL environment info
      shell: bash
      run: |
        cd bbl-state/${{ inputs.env_name }}
        bbl print-env
