name: 'BBL Up'
description: 'Set up test environment using BBL - equivalent to Concourse bbl-up job'

inputs:
  stack:
    description: 'Stack name'
    required: true
  version:
    description: 'Version number'
    required: true
  env_name:
    description: 'Environment name'
    required: false
    default: 'cflinuxfs5'
  gcp_project_id:
    description: 'GCP Project ID'
    required: false
    default: 'cf-buildpacks'
  gcp_zone:
    description: 'GCP Zone'
    required: false
    default: 'us-east1-c'
  gcp_region:
    description: 'GCP Region'
    required: false
    default: 'us-east1'
  lb_domain:
    description: 'Load balancer domain'
    required: false
    default: 'cflinuxfs5.buildpacks-gcp.ci.cf-app.com'

outputs:
  success:
    description: 'Whether BBL up succeeded'
    value: ${{ steps.bbl-up.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Checkout cf-deployment-concourse-tasks
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/cf-deployment-concourse-tasks
        ref: main
        path: cf-deployment-concourse-tasks

    - name: Checkout bosh-deployment
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/bosh-deployment
        ref: master
        path: bosh-deployment

    - name: Checkout buildpacks-envs
      uses: actions/checkout@v4
      with:
        repository: ivo1116/buildpacks-envs
        ref: master
        path: bbl-state
        ssh-key: ${{ env.BUILDPACKS_ENVS_DEPLOY_KEY }}

    - name: Checkout buildpacks-ci
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/buildpacks-ci
        ref: master
        path: buildpacks-ci

    - name: Install BBL and dependencies
      shell: bash
      run: |
        # Install BBL
        wget -O /tmp/bbl https://github.com/cloudfoundry/bosh-bootloader/releases/download/v8.4.110/bbl-v8.4.110_linux_x86-64
        chmod +x /tmp/bbl
        sudo mv /tmp/bbl /usr/local/bin/bbl

        # Install Terraform
        wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        unzip /tmp/terraform.zip -d /tmp/
        sudo mv /tmp/terraform /usr/local/bin/terraform

        # Install BOSH CLI
        wget -O /tmp/bosh https://github.com/cloudfoundry/bosh-cli/releases/download/v7.4.0/bosh-cli-7.4.0-linux-amd64
        chmod +x /tmp/bosh
        sudo mv /tmp/bosh /usr/local/bin/bosh

    - name: BBL Up (No LB)
      id: bbl-up
      shell: bash
      run: |
        set -euo pipefail

        cd bbl-state/${{ inputs.env_name }}

        # Set up environment variables (no LB config)
        export BBL_GCP_SERVICE_ACCOUNT_KEY='${{ env.GCP_SERVICE_ACCOUNT_KEY }}'
        export BBL_GCP_PROJECT_ID='${{ inputs.gcp_project_id }}'
        export BBL_GCP_ZONE='${{ inputs.gcp_zone }}'
        export BBL_GCP_REGION='${{ inputs.gcp_region }}'
        export BBL_IAAS=gcp
        export BBL_ENV_NAME='${{ inputs.env_name }}'

        # Run BBL up without LB configuration
        bbl up \
          --ops-file ../../bosh-deployment/gcp/cpi.yml \
          --ops-file ../../bosh-deployment/jumpbox-user.yml \
          --ops-file ../../bosh-deployment/uaa.yml \
          --ops-file ../../bosh-deployment/credhub.yml \
          --ops-file ../../bosh-deployment/gcp/disable-static-ip.yml

        echo "success=true" >> $GITHUB_OUTPUT
        - name: Add GCP parent DNS record
          shell: bash
          run: |
            cd buildpacks-ci
            
            export GCP_SERVICE_ACCOUNT_KEY='${{ env.GCP_SERVICE_ACCOUNT_KEY }}'
            export ENV_NAME='${{ inputs.env_name }}'
            
            echo "Adding GCP parent DNS record for $ENV_NAME"

    - name: Commit and push BBL state
      shell: bash
      run: |
        cd bbl-state
        
        git config user.name "CF Buildpacks Eng Bot"
        git config user.email "tanzu-buildpacks.pdl@broadcom.com"
        
        if [[ -n "$(git status --porcelain)" ]]; then
          git add -A
          git commit -m "Update bbl state dir for ${{ inputs.env_name }}"
          git push origin HEAD
        fi
